//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSUF.AutoReports.ControlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", ConfigurationName="ControlService.ControlQuerySoap")]
    public interface ControlQuerySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetAllColumns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfAllColumnResults GetAllColumns(string login, string password, int controlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetAllColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfAllColumnResults> GetAllColumnsAsync(string login, string password, int controlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetAllControls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfAllControlResults GetAllControls(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetAllControls", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfAllControlResults> GetAllControlsAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetSelectedControls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfAllControlResults GetSelectedControls(string login, string password, string controlType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetSelectedControls", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfAllControlResults> GetSelectedControlsAsync(string login, string password, string controlType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetControlSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfControlSettingsResults GetControlSettings(string login, string password, int controlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetControlSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfControlSettingsResults> GetControlSettingsAsync(string login, string password, int controlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetOneMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetOneMember(string login, string password, int controlId, string columns, string constituentId, bool includeTransactions, bool includeTransactionDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetOneMember", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetOneMemberAsync(string login, string password, int controlId, string columns, string constituentId, bool includeTransactions, bool includeTransactionDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetOneMemberByMemberId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetOneMemberByMemberId(string login, string password, int controlId, string columns, int memberId, bool includeTransactions, bool includeTransactionDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetOneMemberByMemberId", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetOneMemberByMemberIdAsync(string login, string password, int controlId, string columns, int memberId, bool includeTransactions, bool includeTransactionDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetMembersChangedDuring", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetMembersChangedDuring(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedFrom, System.DateTime changedTo, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetMembersChangedDuring", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetMembersChangedDuringAsync(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedFrom, System.DateTime changedTo, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetMembersChangedSince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetMembersChangedSince(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedSince, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/GetMembersChangedSince", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetMembersChangedSinceAsync(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedSince, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter);
        
        // CODEGEN: Parameter 'MemberInformation' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.UpdateResponse Update(LSUF.AutoReports.ControlService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.UpdateResponse> UpdateAsync(LSUF.AutoReports.ControlService.UpdateRequest request);
        
        // CODEGEN: Parameter 'MemberInformation' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/UpdateKeepChanged", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LSUF.AutoReports.ControlService.UpdateKeepChangedResponse UpdateKeepChanged(LSUF.AutoReports.ControlService.UpdateKeepChangedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://imodules.com/WebServices/ControlQuery/UpdateKeepChanged", ReplyAction="*")]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.UpdateKeepChangedResponse> UpdateKeepChangedAsync(LSUF.AutoReports.ControlService.UpdateKeepChangedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class ArrayOfAllColumnResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AllColumnResults[] allColumnResultsField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllColumnResults", Order=0)]
        public AllColumnResults[] AllColumnResults {
            get {
                return this.allColumnResultsField;
            }
            set {
                this.allColumnResultsField = value;
                this.RaisePropertyChanged("AllColumnResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class AllColumnResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Option[] optionsField;
        
        private string columnField;
        
        private string column_InfoField;
        
        private bool instanceField;
        
        private bool reusableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Option[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
                this.RaisePropertyChanged("Options");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Column_Info {
            get {
                return this.column_InfoField;
            }
            set {
                this.column_InfoField = value;
                this.RaisePropertyChanged("Column_Info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("Instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Reusable {
            get {
                return this.reusableField;
            }
            set {
                this.reusableField = value;
                this.RaisePropertyChanged("Reusable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Option : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string textField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class UpdateInstanceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UpdateColumnResult[] updateColumnResultField;
        
        private Error errorField;
        
        private Message messageField;
        
        private string instance_IdField;
        
        private string external_Id_NameField;
        
        private string external_Id_ValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateColumnResult", Order=0)]
        public UpdateColumnResult[] UpdateColumnResult {
            get {
                return this.updateColumnResultField;
            }
            set {
                this.updateColumnResultField = value;
                this.RaisePropertyChanged("UpdateColumnResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Instance_Id {
            get {
                return this.instance_IdField;
            }
            set {
                this.instance_IdField = value;
                this.RaisePropertyChanged("Instance_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string External_Id_Name {
            get {
                return this.external_Id_NameField;
            }
            set {
                this.external_Id_NameField = value;
                this.RaisePropertyChanged("External_Id_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string External_Id_Value {
            get {
                return this.external_Id_ValueField;
            }
            set {
                this.external_Id_ValueField = value;
                this.RaisePropertyChanged("External_Id_Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class UpdateColumnResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error errorField;
        
        private Message messageField;
        
        private string nameField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class UpdateMemberResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UpdateColumnResult[] updateColumnResultField;
        
        private UpdateInstanceResult[] updateInstanceResultField;
        
        private Error errorField;
        
        private Message messageField;
        
        private int imod_Member_IdField;
        
        private string constituent_IdField;
        
        private bool is_NewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateColumnResult", Order=0)]
        public UpdateColumnResult[] UpdateColumnResult {
            get {
                return this.updateColumnResultField;
            }
            set {
                this.updateColumnResultField = value;
                this.RaisePropertyChanged("UpdateColumnResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateInstanceResult", Order=1)]
        public UpdateInstanceResult[] UpdateInstanceResult {
            get {
                return this.updateInstanceResultField;
            }
            set {
                this.updateInstanceResultField = value;
                this.RaisePropertyChanged("UpdateInstanceResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Imod_Member_Id {
            get {
                return this.imod_Member_IdField;
            }
            set {
                this.imod_Member_IdField = value;
                this.RaisePropertyChanged("Imod_Member_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Constituent_Id {
            get {
                return this.constituent_IdField;
            }
            set {
                this.constituent_IdField = value;
                this.RaisePropertyChanged("Constituent_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Is_New {
            get {
                return this.is_NewField;
            }
            set {
                this.is_NewField = value;
                this.RaisePropertyChanged("Is_New");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class UpdateResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UpdateMemberResult[] updateMemberResultField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateMemberResult", Order=0)]
        public UpdateMemberResult[] UpdateMemberResult {
            get {
                return this.updateMemberResultField;
            }
            set {
                this.updateMemberResultField = value;
                this.RaisePropertyChanged("UpdateMemberResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class LinkedTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int transactionIdField;
        
        private decimal amountField;
        
        private int controlIdField;
        
        private string controlTypeField;
        
        private string controlNameField;
        
        private string paymentTypeField;
        
        private decimal totalScheduledAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ControlId {
            get {
                return this.controlIdField;
            }
            set {
                this.controlIdField = value;
                this.RaisePropertyChanged("ControlId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ControlType {
            get {
                return this.controlTypeField;
            }
            set {
                this.controlTypeField = value;
                this.RaisePropertyChanged("ControlType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ControlName {
            get {
                return this.controlNameField;
            }
            set {
                this.controlNameField = value;
                this.RaisePropertyChanged("ControlName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal TotalScheduledAmount {
            get {
                return this.totalScheduledAmountField;
            }
            set {
                this.totalScheduledAmountField = value;
                this.RaisePropertyChanged("TotalScheduledAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class TransactionItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Column[] columnField;
        
        private int imod_Member_IdField;
        
        private string typeField;
        
        private string transaction_Item_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Column", Order=0)]
        public Column[] Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Imod_Member_Id {
            get {
                return this.imod_Member_IdField;
            }
            set {
                this.imod_Member_IdField = value;
                this.RaisePropertyChanged("Imod_Member_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Transaction_Item_Id {
            get {
                return this.transaction_Item_IdField;
            }
            set {
                this.transaction_Item_IdField = value;
                this.RaisePropertyChanged("Transaction_Item_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Column : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Designation[] designationsField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Designation[] Designations {
            get {
                return this.designationsField;
            }
            set {
                this.designationsField = value;
                this.RaisePropertyChanged("Designations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Designation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Id[] idsField;
        
        private int idField;
        
        private decimal amountField;
        
        private string textField;
        
        private string valueField;
        
        private string designationInstructionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Id[] Ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
                this.RaisePropertyChanged("Ids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DesignationInstructions {
            get {
                return this.designationInstructionsField;
            }
            set {
                this.designationInstructionsField = value;
                this.RaisePropertyChanged("DesignationInstructions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Id : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Column[] columnField;
        
        private TransactionItem[] transactionItemsField;
        
        private LinkedTransaction linkedTransactionField;
        
        private LedgerValue[] ledgerValuesField;
        
        private int transaction_IdField;
        
        private bool isSuccessField;
        
        private bool isReviewedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Column", Order=0)]
        public Column[] Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public TransactionItem[] TransactionItems {
            get {
                return this.transactionItemsField;
            }
            set {
                this.transactionItemsField = value;
                this.RaisePropertyChanged("TransactionItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LinkedTransaction LinkedTransaction {
            get {
                return this.linkedTransactionField;
            }
            set {
                this.linkedTransactionField = value;
                this.RaisePropertyChanged("LinkedTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public LedgerValue[] LedgerValues {
            get {
                return this.ledgerValuesField;
            }
            set {
                this.ledgerValuesField = value;
                this.RaisePropertyChanged("LedgerValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Transaction_Id {
            get {
                return this.transaction_IdField;
            }
            set {
                this.transaction_IdField = value;
                this.RaisePropertyChanged("Transaction_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsReviewed {
            get {
                return this.isReviewedField;
            }
            set {
                this.isReviewedField = value;
                this.RaisePropertyChanged("IsReviewed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class LedgerValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Instance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Column[] columnField;
        
        private Transaction[] transactionsField;
        
        private string instance_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Column", Order=0)]
        public Column[] Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Transaction[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Instance_Id {
            get {
                return this.instance_IdField;
            }
            set {
                this.instance_IdField = value;
                this.RaisePropertyChanged("Instance_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class Guest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iMod_Member_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IMod_Member_Id {
            get {
                return this.iMod_Member_IdField;
            }
            set {
                this.iMod_Member_IdField = value;
                this.RaisePropertyChanged("IMod_Member_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class MemberInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Guest[] guestsField;
        
        private Guest guestOfField;
        
        private Column[] columnField;
        
        private Instance[] instancesField;
        
        private int imod_Member_IdField;
        
        private string constituent_IdField;
        
        private System.DateTime last_UpdatedField;
        
        private bool last_UpdatedFieldSpecified;
        
        private string last_Updated_By_Constituent_IdField;
        
        private string last_Updated_By_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Guest[] Guests {
            get {
                return this.guestsField;
            }
            set {
                this.guestsField = value;
                this.RaisePropertyChanged("Guests");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Guest GuestOf {
            get {
                return this.guestOfField;
            }
            set {
                this.guestOfField = value;
                this.RaisePropertyChanged("GuestOf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Column", Order=2)]
        public Column[] Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Instance[] Instances {
            get {
                return this.instancesField;
            }
            set {
                this.instancesField = value;
                this.RaisePropertyChanged("Instances");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Imod_Member_Id {
            get {
                return this.imod_Member_IdField;
            }
            set {
                this.imod_Member_IdField = value;
                this.RaisePropertyChanged("Imod_Member_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Constituent_Id {
            get {
                return this.constituent_IdField;
            }
            set {
                this.constituent_IdField = value;
                this.RaisePropertyChanged("Constituent_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Last_Updated {
            get {
                return this.last_UpdatedField;
            }
            set {
                this.last_UpdatedField = value;
                this.RaisePropertyChanged("Last_Updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_UpdatedSpecified {
            get {
                return this.last_UpdatedFieldSpecified;
            }
            set {
                this.last_UpdatedFieldSpecified = value;
                this.RaisePropertyChanged("Last_UpdatedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Last_Updated_By_Constituent_Id {
            get {
                return this.last_Updated_By_Constituent_IdField;
            }
            set {
                this.last_Updated_By_Constituent_IdField = value;
                this.RaisePropertyChanged("Last_Updated_By_Constituent_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Last_Updated_By_Name {
            get {
                return this.last_Updated_By_NameField;
            }
            set {
                this.last_Updated_By_NameField = value;
                this.RaisePropertyChanged("Last_Updated_By_Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class ArrayOfMemberInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MemberInformation[] memberInformationField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberInformation", Order=0)]
        public MemberInformation[] MemberInformation {
            get {
                return this.memberInformationField;
            }
            set {
                this.memberInformationField = value;
                this.RaisePropertyChanged("MemberInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class ControlSettingsResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class ArrayOfControlSettingsResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ControlSettingsResults[] controlSettingsResultsField;
        
        private LedgerValue[] ledgerValuesField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ControlSettingsResults", Order=0)]
        public ControlSettingsResults[] ControlSettingsResults {
            get {
                return this.controlSettingsResultsField;
            }
            set {
                this.controlSettingsResultsField = value;
                this.RaisePropertyChanged("ControlSettingsResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LedgerValue[] LedgerValues {
            get {
                return this.ledgerValuesField;
            }
            set {
                this.ledgerValuesField = value;
                this.RaisePropertyChanged("LedgerValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class AllControlResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int control_IdField;
        
        private string control_NameField;
        
        private string control_TypeField;
        
        private int group_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Control_Id {
            get {
                return this.control_IdField;
            }
            set {
                this.control_IdField = value;
                this.RaisePropertyChanged("Control_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Control_Name {
            get {
                return this.control_NameField;
            }
            set {
                this.control_NameField = value;
                this.RaisePropertyChanged("Control_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Control_Type {
            get {
                return this.control_TypeField;
            }
            set {
                this.control_TypeField = value;
                this.RaisePropertyChanged("Control_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Group_Id {
            get {
                return this.group_IdField;
            }
            set {
                this.group_IdField = value;
                this.RaisePropertyChanged("Group_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/")]
    public partial class ArrayOfAllControlResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AllControlResults[] allControlResultsField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllControlResults", Order=0)]
        public AllControlResults[] AllControlResults {
            get {
                return this.allControlResultsField;
            }
            set {
                this.allControlResultsField = value;
                this.RaisePropertyChanged("AllControlResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://imodules.com/WebServices/ControlQuery/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=2)]
        public int controlId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=3)]
        public bool allowAddingConstituents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("MemberInformation")]
        public LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(string login, string password, int controlId, bool allowAddingConstituents, LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation) {
            this.login = login;
            this.password = password;
            this.controlId = controlId;
            this.allowAddingConstituents = allowAddingConstituents;
            this.MemberInformation = MemberInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://imodules.com/WebServices/ControlQuery/", IsWrapped=true)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=0)]
        public LSUF.AutoReports.ControlService.UpdateResults UpdateResult;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(LSUF.AutoReports.ControlService.UpdateResults UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateKeepChanged", WrapperNamespace="http://imodules.com/WebServices/ControlQuery/", IsWrapped=true)]
    public partial class UpdateKeepChangedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=2)]
        public int controlId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=3)]
        public bool allowAddingConstituents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=4)]
        public System.DateTime keepChangedFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=5)]
        public System.DateTime keepChangedTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("MemberInformation")]
        public LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation;
        
        public UpdateKeepChangedRequest() {
        }
        
        public UpdateKeepChangedRequest(string login, string password, int controlId, bool allowAddingConstituents, System.DateTime keepChangedFrom, System.DateTime keepChangedTo, LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation) {
            this.login = login;
            this.password = password;
            this.controlId = controlId;
            this.allowAddingConstituents = allowAddingConstituents;
            this.keepChangedFrom = keepChangedFrom;
            this.keepChangedTo = keepChangedTo;
            this.MemberInformation = MemberInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateKeepChangedResponse", WrapperNamespace="http://imodules.com/WebServices/ControlQuery/", IsWrapped=true)]
    public partial class UpdateKeepChangedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://imodules.com/WebServices/ControlQuery/", Order=0)]
        public LSUF.AutoReports.ControlService.UpdateResults UpdateKeepChangedResult;
        
        public UpdateKeepChangedResponse() {
        }
        
        public UpdateKeepChangedResponse(LSUF.AutoReports.ControlService.UpdateResults UpdateKeepChangedResult) {
            this.UpdateKeepChangedResult = UpdateKeepChangedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControlQuerySoapChannel : LSUF.AutoReports.ControlService.ControlQuerySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlQuerySoapClient : System.ServiceModel.ClientBase<LSUF.AutoReports.ControlService.ControlQuerySoap>, LSUF.AutoReports.ControlService.ControlQuerySoap {
        
        public ControlQuerySoapClient() {
        }
        
        public ControlQuerySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlQuerySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlQuerySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlQuerySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfAllColumnResults GetAllColumns(string login, string password, int controlId) {
            return base.Channel.GetAllColumns(login, password, controlId);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfAllColumnResults> GetAllColumnsAsync(string login, string password, int controlId) {
            return base.Channel.GetAllColumnsAsync(login, password, controlId);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfAllControlResults GetAllControls(string login, string password) {
            return base.Channel.GetAllControls(login, password);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfAllControlResults> GetAllControlsAsync(string login, string password) {
            return base.Channel.GetAllControlsAsync(login, password);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfAllControlResults GetSelectedControls(string login, string password, string controlType) {
            return base.Channel.GetSelectedControls(login, password, controlType);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfAllControlResults> GetSelectedControlsAsync(string login, string password, string controlType) {
            return base.Channel.GetSelectedControlsAsync(login, password, controlType);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfControlSettingsResults GetControlSettings(string login, string password, int controlId) {
            return base.Channel.GetControlSettings(login, password, controlId);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfControlSettingsResults> GetControlSettingsAsync(string login, string password, int controlId) {
            return base.Channel.GetControlSettingsAsync(login, password, controlId);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetOneMember(string login, string password, int controlId, string columns, string constituentId, bool includeTransactions, bool includeTransactionDetails) {
            return base.Channel.GetOneMember(login, password, controlId, columns, constituentId, includeTransactions, includeTransactionDetails);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetOneMemberAsync(string login, string password, int controlId, string columns, string constituentId, bool includeTransactions, bool includeTransactionDetails) {
            return base.Channel.GetOneMemberAsync(login, password, controlId, columns, constituentId, includeTransactions, includeTransactionDetails);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetOneMemberByMemberId(string login, string password, int controlId, string columns, int memberId, bool includeTransactions, bool includeTransactionDetails) {
            return base.Channel.GetOneMemberByMemberId(login, password, controlId, columns, memberId, includeTransactions, includeTransactionDetails);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetOneMemberByMemberIdAsync(string login, string password, int controlId, string columns, int memberId, bool includeTransactions, bool includeTransactionDetails) {
            return base.Channel.GetOneMemberByMemberIdAsync(login, password, controlId, columns, memberId, includeTransactions, includeTransactionDetails);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetMembersChangedDuring(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedFrom, System.DateTime changedTo, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter) {
            return base.Channel.GetMembersChangedDuring(login, password, controlId, columns, changedColumns, changedFrom, changedTo, includeNonMembers, includeBlankIds, includeTransactions, includeTransactionDetails, includeUnreviewed, filter);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetMembersChangedDuringAsync(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedFrom, System.DateTime changedTo, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter) {
            return base.Channel.GetMembersChangedDuringAsync(login, password, controlId, columns, changedColumns, changedFrom, changedTo, includeNonMembers, includeBlankIds, includeTransactions, includeTransactionDetails, includeUnreviewed, filter);
        }
        
        public LSUF.AutoReports.ControlService.ArrayOfMemberInformation GetMembersChangedSince(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedSince, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter) {
            return base.Channel.GetMembersChangedSince(login, password, controlId, columns, changedColumns, changedSince, includeNonMembers, includeBlankIds, includeTransactions, includeTransactionDetails, includeUnreviewed, filter);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.ArrayOfMemberInformation> GetMembersChangedSinceAsync(string login, string password, int controlId, string columns, string changedColumns, System.DateTime changedSince, bool includeNonMembers, bool includeBlankIds, bool includeTransactions, bool includeTransactionDetails, bool includeUnreviewed, string filter) {
            return base.Channel.GetMembersChangedSinceAsync(login, password, controlId, columns, changedColumns, changedSince, includeNonMembers, includeBlankIds, includeTransactions, includeTransactionDetails, includeUnreviewed, filter);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LSUF.AutoReports.ControlService.UpdateResponse LSUF.AutoReports.ControlService.ControlQuerySoap.Update(LSUF.AutoReports.ControlService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public LSUF.AutoReports.ControlService.UpdateResults Update(string login, string password, int controlId, bool allowAddingConstituents, LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation) {
            LSUF.AutoReports.ControlService.UpdateRequest inValue = new LSUF.AutoReports.ControlService.UpdateRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.controlId = controlId;
            inValue.allowAddingConstituents = allowAddingConstituents;
            inValue.MemberInformation = MemberInformation;
            LSUF.AutoReports.ControlService.UpdateResponse retVal = ((LSUF.AutoReports.ControlService.ControlQuerySoap)(this)).Update(inValue);
            return retVal.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.UpdateResponse> LSUF.AutoReports.ControlService.ControlQuerySoap.UpdateAsync(LSUF.AutoReports.ControlService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.UpdateResponse> UpdateAsync(string login, string password, int controlId, bool allowAddingConstituents, LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation) {
            LSUF.AutoReports.ControlService.UpdateRequest inValue = new LSUF.AutoReports.ControlService.UpdateRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.controlId = controlId;
            inValue.allowAddingConstituents = allowAddingConstituents;
            inValue.MemberInformation = MemberInformation;
            return ((LSUF.AutoReports.ControlService.ControlQuerySoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LSUF.AutoReports.ControlService.UpdateKeepChangedResponse LSUF.AutoReports.ControlService.ControlQuerySoap.UpdateKeepChanged(LSUF.AutoReports.ControlService.UpdateKeepChangedRequest request) {
            return base.Channel.UpdateKeepChanged(request);
        }
        
        public LSUF.AutoReports.ControlService.UpdateResults UpdateKeepChanged(string login, string password, int controlId, bool allowAddingConstituents, System.DateTime keepChangedFrom, System.DateTime keepChangedTo, LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation) {
            LSUF.AutoReports.ControlService.UpdateKeepChangedRequest inValue = new LSUF.AutoReports.ControlService.UpdateKeepChangedRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.controlId = controlId;
            inValue.allowAddingConstituents = allowAddingConstituents;
            inValue.keepChangedFrom = keepChangedFrom;
            inValue.keepChangedTo = keepChangedTo;
            inValue.MemberInformation = MemberInformation;
            LSUF.AutoReports.ControlService.UpdateKeepChangedResponse retVal = ((LSUF.AutoReports.ControlService.ControlQuerySoap)(this)).UpdateKeepChanged(inValue);
            return retVal.UpdateKeepChangedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.UpdateKeepChangedResponse> LSUF.AutoReports.ControlService.ControlQuerySoap.UpdateKeepChangedAsync(LSUF.AutoReports.ControlService.UpdateKeepChangedRequest request) {
            return base.Channel.UpdateKeepChangedAsync(request);
        }
        
        public System.Threading.Tasks.Task<LSUF.AutoReports.ControlService.UpdateKeepChangedResponse> UpdateKeepChangedAsync(string login, string password, int controlId, bool allowAddingConstituents, System.DateTime keepChangedFrom, System.DateTime keepChangedTo, LSUF.AutoReports.ControlService.MemberInformation[] MemberInformation) {
            LSUF.AutoReports.ControlService.UpdateKeepChangedRequest inValue = new LSUF.AutoReports.ControlService.UpdateKeepChangedRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.controlId = controlId;
            inValue.allowAddingConstituents = allowAddingConstituents;
            inValue.keepChangedFrom = keepChangedFrom;
            inValue.keepChangedTo = keepChangedTo;
            inValue.MemberInformation = MemberInformation;
            return ((LSUF.AutoReports.ControlService.ControlQuerySoap)(this)).UpdateKeepChangedAsync(inValue);
        }
    }
}
